version: '3.4'
services:
  traefik:
    image: traefik:v1.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - proxy1
      - proxy2
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  proxy1:
  proxy2:
