version: "3.4"
volumes:
  logs_api:
    driver: local
  logs_subdomains:
    driver: local
  logs_adminer:
    driver: local
  mariadb:
    driver: local
networks:
  traefik:
    external:
      name: traefik_proxy2
services:
  api:
    image: nginx:latest
    volumes:
      - /var/www/codeheures/api:/var/www/codeheures/api
      - logs_api:/var/logs
      - ./api.conf:/etc/nginx/conf.d/api.conf
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.backend=api-codeheures"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:api.codeheures.test"
  subdomains:
    image: nginx:latest
    volumes:
    - /var/www/codeheures:/var/www/codeheures
    - /var/www/ace-services:/var/www/ace-services
    - logs_subdomains:/var/logs
    - ./subdomains.conf:/etc/nginx/conf.d/subdomains.conf
    networks:
    - traefik
    deploy:
      replicas: 1
      labels:
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
      - "traefik.backend=subdomains-codeheures"
      - "traefik.enable=true"
      - "traefik.poem.frontend.rule=Host:poem.codeheures.test"
      - "traefik.ficheproduit.frontend.rule=Host:ficheproduit.codeheures.test"
      - "traefik.edania.frontend.rule=Host:edania.codeheures.test"
      - "traefik.frigo.frontend.rule=Host:frigo.codeheures.test"
      - "traefik.lpatccms.frontend.rule=Host:lpatc-cms.codeheures.test"
      - "traefik.docs.frontend.rule=Host:docs.codeheures.test"
      - "traefik.aceservices.frontend.rule=Host:ace-services.codeheures.test"
  adminer:
    image: nginx:latest
    volumes:
      - /var/www/adminer:/var/www/adminer
      - logs_adminer:/var/logs
      - ./adminer.conf:/etc/nginx/conf.d/adminer.conf
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.backend=adminer-codeheures"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:adminer.codeheures.test"
        - "traefik.frontend.auth.basic=sylvain:$$apr1$$YuXSTghB$$ED5vjLJdNctJ14BVWQFsC1"
  php:
    image: codeheures/php-fpm:v1
    volumes:
      - /var/www:/var/www
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mariadb:/var/lib/mysql
    networks:
    - traefik
    deploy:
      replicas: 1
      labels:
      - "traefik.enable=false"
  front:
    image: codeheures/npm:v1
    volumes:
      - /var/www/codeheures/front:/var/www/codeheures/front
    working_dir: /var/www/codeheures/front
    command: npm run dev
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=8002"
        - "traefik.backend=codeheures"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:codeheures.test"