#!/bin/bash
source $(dirname "$BASH_SOURCE[0]")/images_names

# docker
alias whoIsDockerPhp='docker container ls | grep ${CODEHEURES_PHP_IMAGE} | awk '\''{print $1 }'\'''
alias whoIsDockerNpm='docker container ls | grep ${CODEHEURES_NPM_IMAGE} | awk '\''{print $1 }'\'''
alias php='docker exec -ti -w $(pwd) $(whoIsDockerPhp) php'
alias composer='docker exec -ti -w $(pwd) $(whoIsDockerPhp) composer'
alias logsnpm='docker container logs --follow $(whoIsDockerNpm)'