#!/bin/bash
source $(dirname "$BASH_SOURCE[0]")/images_names

RECONFIGURE_ALL=0
RESTART=0
STACK_NAME=0
DEV=1
PROD=0



while test $# -gt 0
do
    case "$1" in
        --reconfigure-all) RECONFIGURE_ALL=1
            ;;
        --restart) RESTART=1
            ;;
        --dev) DEV=1
            ;;
        --prod) PROD=1
	    ;;
        --*) echo "bad option $1"
            ;;
        *) STACK_NAME=$1
            ;;
    esac
    shift
done

echo "stackname = ${STACK_NAME}"
echo "reconfigure all: ${RECONFIGURE_ALL}"
echo "restart: ${RESTART}"
echo "is Dev: ${DEV}"
echo "is prod: ${PROD}"
echo "launch command: docker stack deploy -c ${CODEHEURES_DOCKER_CONFIG_ROOT}/stacks/${STACK_NAME}/${file} ${STACK_NAME}"

if [ ${STACK_NAME} = 0 ]; then
  echo ERROR: Bad stack name ${STACK_NAME} 1>&2
  exit 1;
fi

if [ ${RECONFIGURE_ALL} = 1 ]; then
  source ${CODEHEURES_DOCKER_CONFIG_ROOT}/images/builds && docker stack rm ${STACK_NAME} && sleep 10
fi

if [ ${RESTART} = 1 ]; then
  docker stack rm ${STACK_NAME} && sleep 10
fi

if [ ${DEV} = 1 ]; then
  file=${STACK_NAME}-compose-dev.yml
fi

if [ ${PROD} = 1 ]; then
  file=${STACK_NAME}-compose-prod.yml
fi

docker stack deploy -c ${CODEHEURES_DOCKER_CONFIG_ROOT}/stacks/${STACK_NAME}/${file} ${STACK_NAME}
