version: "3.4"
volumes:
  logs_api:
    driver: local
  logs_adminer:
    driver: local
  redis:
    driver: local
  elastic:
    driver: local
networks:
  traefik:
    external:
      name: traefik_proxy1
services:
  api:
    image: nginx:latest
    volumes:
      - /var/www/selfjob/api:/var/www/selfjob/api
      - logs_api:/var/logs
      - ./api.conf:/etc/nginx/conf.d/api.conf
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.backend=api-selfjob"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:api-selfjob.codeheures.fr"
  adminer:
    image: nginx:latest
    volumes:
      - /var/www/adminer:/var/www/adminer
      - logs_adminer:/var/logs
      - ./adminer.conf:/etc/nginx/conf.d/adminer.conf
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.backend=adminer-selfjob"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:adminer-selfjob.codeheures.fr"
        - "traefik.frontend.auth.basic=sylvain:$$apr1$$YuXSTghB$$ED5vjLJdNctJ14BVWQFsC1"
  php:
    image: codeheures/php-fpm:v1
    volumes:
      - /var/www:/var/www
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  laravel_echo:
    image: codeheures/laravel-echo:v1
    volumes:
      - /var/www/selfjob/api:/var/www/selfjob/api
    working_dir: /var/www/selfjob/api
    command: laravel-echo-server start
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=6001"
        - "traefik.backend=echo-selfjob"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:echo-selfjob.codeheures.fr"
  frontv2:
    image: codeheures/npm:v1
    volumes:
      - /var/www/selfjob/frontv2:/var/www/selfjob/frontv2
    working_dir: /var/www/selfjob/frontv2
    command: bash -c "npm run build && npm run start"
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=8002"
        - "traefik.backend=selfjob"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:selfjob.codeheures.fr"
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  elasticsearch:
    image: codeheures/elasticsearch:v1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=9200"
        - "traefik.backend=elastic-selfjob"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:elastic-selfjob.codeheures.fr"
        - "traefik.frontend.auth.basic=sylvain:$$apr1$$rgfeb6lD$$JSRW/vK.NVjd94FOo.zdC/"