version: '3.4'
services:
  traefik:
    image: traefik
    command: --web --docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - proxy
networks:
  proxy: