version: "3.4"
volumes:
  logs_aceservices:
    driver: local
  logs_adminer:
    driver: local
  mariadb:
    driver: local
networks:
  traefik:
    external:
      name: traefik_proxyaceservices
services:
  aceservices:
    image: nginx:latest
    volumes:
      - /var/www/ace-services:/var/www/ace-services
      - logs_aceservices:/var/logs
      - ./aceservices.conf:/etc/nginx/conf.d/aceservices.conf
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.backend=aceservices"
        - "traefik.enable=true"
        - "traefik.aceservices.frontend.rule=Host:ace-services.codeheures.fr"
  adminer:
    image: nginx:latest
    volumes:
      - /var/www/adminer:/var/www/adminer
      - logs_adminer:/var/logs
      - ./adminer-aceservices.conf:/etc/nginx/conf.d/adminer-aceservices.conf
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.backend=adminer-aceservices"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:adminer-aceservices.codeheures.fr"
        - "traefik.frontend.auth.basic=sylvain:$$apr1$$YuXSTghB$$ED5vjLJdNctJ14BVWQFsC1"
  php:
    image: codeheures/php-fpm:v1
    volumes:
      - /var/www:/var/www
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mariadb:/var/lib/mysql
    networks:
    - traefik
    deploy:
      replicas: 1
      labels:
      - "traefik.enable=false"